
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        files: "(docs|.github/ISSUE_TEMPLATE)/.*"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        name: mypy src
        files: src/.*
        additional_dependencies:
          - types-python-dateutil
          - types-pytz
          - types-requests
          - types-setuptools
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest src/tests --versions ''
        language: system
        pass_filenames: false
        exclude: ".*.md"
