site_name: AI-on-Demand REST API
site_url: https://api.aiod.eu/docs
repo_url: https://github.com/aiondemand/AIOD-rest-api
edit_uri: edit/develop/docs/
theme:
  name: material
  features:
    - content.code.copy
    - navigation.footer
    - content.action.view
    - content.action.edit
  icon:
    edit: material/pencil
    view: material/eye

nav:
  - Home: README.md
  - Using the API:
      - using/index.md
      - 'Uploading Metadata': using/upload.md
  - Hosting the API:
      - hosting/index.md
      - 'Authentication': hosting/authentication.md
      - 'Connectors': hosting/connectors.md
      - 'Synchronization': hosting/synchronization.md
  - 'Developer Resources':
      - developer/index.md
      - 'Authentication': developer/authentication.md
      - 'User Model': developer/users.md
      - 'Metadata Schema':
          - developer/schema/index.md
          - 'Attributes': developer/schema/attributes.md
          - 'Relationships': developer/schema/relationships.md
          - 'Objects': developer/schema/objects.md
          - 'Schema Migration': developer/schema/migration.md
      - 'Elastic Search': developer/elastic_search.md
      - 'Scripts': developer/scripts.md
      - 'Release Workflow': developer/releases.md
      - 'Troubleshooting': developer/troubleshooting.md
  - 'Contributing': contributing.md

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - section-index
  - search
