import abc
from http import HTTPStatus

from fastapi import APIRouter, HTTPException
from sqlmodel import SQLModel, select
from starlette.status import HTTP_404_NOT_FOUND, HTTP_500_INTERNAL_SERVER_ERROR

from database.model.concept.concept import AIoDConcept
from database.model.helper_functions import non_abstract_subclasses
from database.session import DbSession
from routers import resource_routers


class ParentRouter(abc.ABC):
    """
    Abstract class for FastAPI parent-class routers. These are routers for, for example, Agent,
    making it possible to perform a GET request based on the agent_identifier, retrieving either
    an Organisation or a Person.
    """

    @property
    @abc.abstractmethod
    def resource_name(self) -> str:
        """The name of the resource. E.g. 'agent'"""

    @property
    @abc.abstractmethod
    def resource_name_plural(self) -> str:
        """The plural of the name of the resource. E.g. 'agents'"""

    @property
    @abc.abstractmethod
    def parent_class(self):
        """The resource type. E.g. Agent"""

    @property
    @abc.abstractmethod
    def parent_class_table(self):
        """The table class of the resource. E.g. AgentTable"""

    def create(self, url_prefix: str) -> APIRouter:
        router = APIRouter()
        version = "v1"
        default_kwargs = {
            "response_model_exclude_none": True,
            "tags": ["parents"],
        }
        available_schemas: list[SQLModel] = list(non_abstract_subclasses(self.parent_class))
        classes_dict = {clz.__tablename__: clz for clz in available_schemas if clz.__tablename__}
        routers = {router.resource_name: router for router in resource_routers.router_list}
        read_classes_dict = {name: routers[name].resource_class_read for name in classes_dict}

        get_resource = self.get_resource_func(classes_dict, read_classes_dict)

        # We cannot simply work with the response_model or return type annotations, since this will
        # cast all responses to the first very loose match, effectively returning only the fields
        # shared on the first match. For more, see:
        # https://github.com/fastapi/fastapi/discussions/6826#discussioncomment-5132149
        # Instead, we manually define the openapi_extra field, which overwrites the responses schema
        # without interfering with parsing. The result is the same schema as if it was generated by
        # FastAPI based on return types, without the restrictions to output.
        # We do provide a slightly more informative schema title though.
        schema_title = f"Response Any {self.resource_name.replace('_', ' ')} {version}"
        # We currently rely on the assets already being defined, which is safe since we use the
        # classes from resource routers. Otherwise, you may need to use Pydantic's v1 .schema()
        # or v2 .model_json_schema() from the generated classes.
        responses = [
            {"$ref": f"#/components/schemas/{clz.__name__}"} for clz in read_classes_dict.values()
        ]  # type: ignore
        openapi_extra = {
            "responses": {
                HTTPStatus.OK: {
                    "description": "Successful Response",
                    "content": {
                        "application/json": {
                            "schema": {
                                "title": schema_title,
                                "anyOf": responses,
                            },
                        }
                    },
                }
            }
        }

        for path in [
            url_prefix + f"/{self.resource_name_plural}/{version}/{{identifier}}",
            url_prefix + f"/v2/{self.resource_name_plural}/{{identifier}}",
            url_prefix + f"/{self.resource_name_plural}/{{identifier}}",
        ]:
            router.add_api_route(
                path=path,
                endpoint=get_resource,
                openapi_extra=openapi_extra,
                name=self.resource_name,
                **default_kwargs,
            )
        return router

    def get_resource_func(self, classes_dict: dict, read_classes_dict: dict):
        def get_resource(identifier: str):
            with DbSession() as session:
                query = select(self.parent_class_table).where(
                    self.parent_class_table.identifier == identifier
                )
                parent_resource = session.scalars(query).first()
                if not parent_resource:
                    self.raise_404(identifier)
                child_type: str = parent_resource.type
                child_class = classes_dict[child_type]
                child_class_read = read_classes_dict[child_type]
                identifier_name = (
                    self.resource_name + "_id"
                    if hasattr(child_class, self.resource_name + "_id")
                    else self.resource_name + "_identifier"
                )

                query_child = select(child_class).where(
                    getattr(child_class, identifier_name) == identifier
                )
                child: AIoDConcept = session.scalars(query_child).first()
                if child.date_deleted is not None:
                    self.raise_404(identifier)

                if not child:
                    raise HTTPException(
                        status_code=HTTP_500_INTERNAL_SERVER_ERROR,
                        detail=f"The parent could be found, but the child ({child_type}) was not "
                        f"found in our database",
                    )
                return child_class_read.from_orm(child)

        return get_resource

    def raise_404(self, identifier: str):
        raise HTTPException(
            status_code=HTTP_404_NOT_FOUND,
            detail=f"{self.resource_name} with identifier {identifier} not found.",
        )
