"""
Functionality to generate a separate read resource and create resource. For example,
the date_modified should be in the read resource, but not in the create resource. You should
not be able to modify this date yourself in a POST request, but you should retrieve it in a GET
request.
"""

import functools
from typing import Type, Tuple, TYPE_CHECKING, Optional

from pydantic import create_model
from sqlmodel import SQLModel, Field
from sqlmodel.main import FieldInfo

from database.model.annotations import all_annotations
from database.model.helper_functions import get_relationships
from database.model.serializers import create_getter_dict
from database.model.field_length import IDENTIFIER_LENGTH

if TYPE_CHECKING:
    from database.model.concept.concept import AIoDConcept
    from database.model.platform.platform import Platform
    from database.model.relationships import _ResourceRelationship


def _get_field_definitions_read(
    resource_class: Type["AIoDConcept"], relationships: dict[str, "_ResourceRelationship"]
) -> dict[str, Tuple[Type, FieldInfo]]:
    if not hasattr(resource_class, "RelationshipConfig"):
        return {}
    annotations = all_annotations(resource_class.RelationshipConfig)
    return {
        attribute_name: (
            annotations[attribute_name]
            if config.class_read is None
            else config.class_read,  # the type
            config.field(),  # The Field()
        )
        for attribute_name, config in relationships.items()
    }


def _get_field_definitions_create(
    resource_class: Type["AIoDConcept"], relationships: dict[str, "_ResourceRelationship"]
) -> dict[str, Tuple[Type, FieldInfo]]:
    if not hasattr(resource_class, "RelationshipConfig"):
        return {}
    annotations = all_annotations(resource_class.RelationshipConfig)
    return {
        attribute_name: (
            annotations[attribute_name]
            if config.class_create is None
            else config.class_create,  # the type
            config.field(),  # The Field()
        )
        for attribute_name, config in relationships.items()
        if config.include_in_create
    }


@functools.cache  # For Pydantic 'bug', see note at `resource_read`
def resource_create(resource_class: Type["AIoDConcept"] | Type["Platform"]) -> Type[SQLModel]:
    """
    Create a SQLModel for a Create class of a resource. This Create class is a Pydantic class
    that can be used for POST and PUT requests (and thus has no identifier), and is not backed by a
    ORM table.

    Besides the default attributes, this class has the Pydantic-version of the relationships. If the
    resource has a relationship to an "enum table", for instance, this will just be a string value
    in this Create class.

    See https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/ for background.
    """
    relationships = get_relationships(resource_class)
    field_definitions = _get_field_definitions_create(resource_class, relationships)
    model = create_model(
        resource_class.__name__ + "Create", __base__=resource_class.__base__, **field_definitions
    )
    return model


# We cache this not for performance reason, but because if the model would be created multiple times,
# this leads to a conflicting state in the Pydantic model map, erasing the older model.
# Related to https://github.com/fastapi/fastapi/issues/4191 and might be fixed by upgrading to the
# latest Pydantic version
@functools.cache
def resource_read(resource_class: Type["AIoDConcept"] | Type["Platform"]) -> Type[SQLModel]:
    """
    Create a SQLModel for a Read class of a resource. This Read class is a Pydantic class
    that can be used for GET requests (and thus has a required identifier), and is not backed by a
    ORM table.

    Besides the default attributes, this class has the Pydantic-version of the relationships. If the
    resource has a relationship to an "enum table", for instance, this will just be a string value
    in this Read class.

    See https://sqlmodel.tiangolo.com/tutorial/fastapi/multiple-models/ for background.
    """
    # Gets the nested RelationshipConfig class' attributes as dict[attr name, attr value]
    # Ignores attributes marked as private
    relationships = get_relationships(resource_class)

    # Gets all the annotations from the resource_class relationship config
    # and return dict[attr name, (annotation, Field())]
    # Field() is generated by us in relationships.py's `_ResourceRelationship`,
    # result from calling _ResourceRelationship.Field(...)
    # allows for defining the Pydantic attribute corresponding the relationship.
    field_definitions = _get_field_definitions_read(resource_class, relationships)

    # Add custom attributes -- note that it follows the same pattern: (type, Field())
    field_definitions.update({"identifier": (str, Field(max_length=IDENTIFIER_LENGTH))})

    # Create the Pydantic model, inheritance from resource_class.__base__ ensures propagation of
    # 'simple' types that don't have a relationship, such as `is_accessible_for_free: bool`.
    # Some 'simple' attributes, such as `identifier` may be defined on the ORM class instead,
    # which is *not* inherited from by the new pydantic model: resource_class.__base__
    # doesn't work with multiple inheritance it seems (no source, but `__base__` is
    # the singular first parent class). This is why it needed to be added explicitly above.
    model = create_model(
        resource_class.__name__ + "Read", __base__=resource_class.__base__, **field_definitions
    )

    # Attach a `GetterDict` to the Pydantic model based on the relationships defined on `resource_class`,
    # dict[attr name, serializer]. This will take care to serialize the attribute accordingly.
    _update_model_serialization(resource_class, model)
    return model


def _update_model_serialization(resource_class: Type[SQLModel], resource_class_read):
    """
    For every Serializer defined on the RelationshipConfig of the resource, use this Serializer in
    a newly created GetterDict (this is Pydantic functionality) and put in on the config of this
    resource.
    """
    relationships = get_relationships(resource_class)
    if hasattr(resource_class, "RelationshipConfig"):
        getter_dict = create_getter_dict(
            {
                attribute_name: relationshipConfig.serializer
                for attribute_name, relationshipConfig in relationships.items()
                if relationshipConfig.serializer is not None
            }
        )
        resource_class_read.__config__.getter_dict = getter_dict
