# Configures the REST API
# TODO: refactor configuration (https://github.com/aiondemand/AIOD-rest-api/issues/82)

# Information on which database to connect to
[database]
host = "sqlserver"
port = 3306
database = "aiod"
username = "root"
password = "ok"

# One of: 'never', 'if-absent', or 'drop-then-build'
# Determines if the database is created:
#    - never:
#        *never* creates the database, not even if there does not exist one yet.
#        Use this only if you expect the database to be created through other means, such
#        as MySQL group replication.
#    - if-absent:
#        Creates a database only if none exists.
#    - drop-then-build:
#        Drops the database on startup to recreate it from scratch.
#        THIS REMOVES ALL DATA PERMANENTLY. NO RECOVERY POSSIBLE.
build_database = "if-absent"

# Additional options for development
[dev]
reload = false
request_timeout = 10  # seconds
log_level = "INFO"  # Python log levels: https://docs.python.org/3/library/logging.html#logging-levels
disable_reviews = false  # set to true to automatically publish submissions
url_prefix = ""

# Authentication and authorization
[keycloak]
server_url = "http://keycloak:8080/aiod-auth/"
realm = "aiod"
client_id = "aiod-api"  # a private client, used by the backend
client_id_swagger = "aiod-api-swagger"  # a public client, used by the Swagger Frontend
openid_connect_url = "http://localhost/aiod-auth/realms/aiod/.well-known/openid-configuration"
scopes = "openid profile roles"
